### ISSUE TITLE
Drawer App Icon Using Material Design

### ISSUE THREAD

**Issue by SweetLion** [yassirh/digital-ocean-swimmer#47]
Hey, I love the DO Swimmer and the magnificent Material Design. Could you please update the app icon too? It does not fit the design of the app itself. Perhaps someone can help you with the icon. Unfortunately, I do not have any icon design skills...

**Comment by yassirh** [comment]
@SweetLion Neither do I. but if someone has to offer anything I'm interested

**Comment by SweetLion** [comment]
I found someone. Which sizes do you need?

**Comment by yassirh** [comment]
That is great a 512 by 512 is enough but i wouldn't mind a bigger version :)

**Comment by SweetLion** [comment]
![icon_512-x-512](https://cloud.githubusercontent.com/assets/12447257/11953542/67719a92-a8a1-11e5-82eb-a0572895d02c.png)
![icon_1024-x-1024](https://cloud.githubusercontent.com/assets/12447257/11953543/6772eab4-a8a1-11e5-8bf8-b39f73dd06e2.png)

**Comment by yassirh** [comment]
@SweetLion Thank you! i will change the icon

**Comment by SweetLion** [comment]
Icon by Sajid Shaik
https://plus.google.com/+DroidAppsReviewer

**Comment by SweetLion** [comment]
[DigitalOcean Swimmer.zip](https://github.com/yassirh/digital-ocean-swimmer/files/87997/DigitalOcean.Swimmer.zip)

**Comment by JeffreyBearden** [comment]
Hi @yassirh, can you please change the icon on the Google Play website (https://play.google.com/store/apps/details?id=com.yassirh.digitalocean) in the developer console and on https://www.digitalocean.com/community/projects/swimmer too please? Thank you very much. I love the new Material icon!
