### ISSUE TITLE
SF1 only location available for creating a new droplet.

### ISSUE THREAD

**Issue by shinradev** [yassirh/digital-ocean-swimmer#49]
Cannot choose any other location besides SF1 when spinning up a new droplet in the app. https://i.imgur.com/8qra6mt.png

**Comment by yassirh** [comment]
Can you refresh the regions? also can you verify via the dashboard that you can effectively create droplets on other regions?

**Comment by shinradev** [comment]
I was had a backup image selected, thus only available on that one server. Duh.

**Comment by yassirh** [comment]
@shinradev I see! if you want to be able to use it on an other region you will have to transfer it to your desired region (can be done with the app).
